version: '3'

networks:
  proxy:
    external: true

services:
  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: 'portainer'
    restart: 'unless-stopped'
    ports:
      - '8000:8000'
      - '9443:9443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/docker-apps/portainer:/data
