version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  website:
    image: hw100/personalsite:latest
    container_name: personalsite
    networks:
      - proxy
      - internal
    expose:
      - "3000"
    restart: always
    # Remove the ports section since we'll be using nginx proxy manager
